# About App
name: starter_project_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

# App Dependencies
dependencies:

  # Flutter SDK
  flutter:
    sdk: flutter

  # IOS icons
  cupertino_icons: ^1.0.2

  # GetX state-management
  get: ^4.6.5

  # API requesting
  http: ^0.13.5

  # Secondary API requesting
  dio: ^4.0.6

  # onBoarding Screen
  introduction_screen: ^3.0.2

  # Real-Time internet checker
  internet_connection_checker: ^0.0.1+4

  # Get-Storage
  get_storage: ^2.0.3
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  google_sign_in: ^5.4.1


# Dev Dependencies
dev_dependencies:

  # Flutter SDK
  flutter_test:
    sdk: flutter

  # FLutter Rules
  flutter_lints: ^2.0.0
  
  # Flutter Splash Screen 
  flutter_native_splash: ^2.2.9

# Splash Screen Config
flutter_native_splash: 
  color: "#ffffff"
  image: assets/icons/appicon.png

# App Config
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/