# About App
name: starter_project_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

# App Dependencies
dependencies:

  # Flutter SDK
  flutter:
    sdk: flutter

  # IOS icons
  cupertino_icons: ^1.0.2

  # GetX state-management
  get: ^4.6.5
  http: ^0.13.5
  dio: ^4.0.6

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# App Config
flutter:
  uses-material-design: true
  assets:
    - assets/images
    - assets/icons
    - assets/videos
  