# About App
name: starter_project_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

# App Dependencies
dependencies:

  # Flutter SDK
  flutter:
    sdk: flutter

  # IOS icons
  cupertino_icons: ^1.0.2

  # GetX state-management
  get: ^4.6.5

  # API requesting
  http: ^0.13.5

  # Secondary API requesting
  dio: ^4.0.6

  # onBoarding Screen
  introduction_screen: ^3.0.2
  internet_connection_checker: ^0.0.1+4
  get_storage: ^2.0.3
  shared_preferences: ^2.0.15

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  flutter_native_splash: ^2.2.9

flutter_native_splash: 
  color: "#ffffff"
  image: assets/icons/appicon.png

# App Config
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
  